-- Пользователи
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    login VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    birthday DATE NOT NULL
);

-- Рейтинг MPA
CREATE TABLE IF NOT EXISTS mpa (
    id INT PRIMARY KEY,
    name VARCHAR(20) NOT NULL
);

-- Жанры
CREATE TABLE IF NOT EXISTS genres (
    id INT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

-- Фильмы
CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    release_date DATE NOT NULL,
    duration INT NOT NULL,
    mpa_id INT,
    CONSTRAINT fk_film_mpa
        FOREIGN KEY (mpa_id)
        REFERENCES mpa(id)
);

-- Связь "фильм - жанр"
CREATE TABLE IF NOT EXISTS film_genres (
    film_id BIGINT NOT NULL,
    genre_id INT NOT NULL,

    PRIMARY KEY (film_id, genre_id),

    CONSTRAINT fk_fg_film
        FOREIGN KEY (film_id)
        REFERENCES films(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_fg_genre
        FOREIGN KEY (genre_id)
        REFERENCES genres(id)
);

-- Лайки фильмов
CREATE TABLE IF NOT EXISTS film_likes (
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,

    PRIMARY KEY (film_id, user_id),

    CONSTRAINT fk_like_film
        FOREIGN KEY (film_id)
        REFERENCES films(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_like_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

-- Статусы дружбы
CREATE TABLE IF NOT EXISTS friendship_statuses (
    id INT PRIMARY KEY,
    name VARCHAR(20) NOT NULL
);

-- Дружба пользователей
CREATE TABLE IF NOT EXISTS friendships (
    user_id BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    status_id INT NOT NULL,

    PRIMARY KEY (user_id, friend_id),

    CONSTRAINT fk_friend_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_friend_friend
        FOREIGN KEY (friend_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_friend_status
        FOREIGN KEY (status_id)
        REFERENCES friendship_statuses(id)
);